version: '3.7'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3456:3456
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/app/
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "nba_stats"
      MYSQL_DATABASE: "nba"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  default:
volumes:
  mysql_data: